# Generated by Django 4.0 on 2024-04-09 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
