# Generated by Django 5.0.4 on 2024-04-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlylist',
            name='unit',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
