# Generated by Django 5.0.4 on 2024-04-23 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0007_alter_monthlylist_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlylist',
            name='unit',
        ),
    ]
