# Generated by Django 5.0.4 on 2024-04-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0008_remove_monthlylist_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlylist',
            name='unit',
            field=models.CharField(default='GRM', max_length=50),
        ),
    ]
