# Generated by Django 4.0 on 2024-04-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phn_no', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('nationality', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('website', models.EmailField(blank=True, max_length=254, null=True)),
                ('maritial_status', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('company_name', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('desc', models.TextField()),
                ('project_name', models.CharField(max_length=50)),
                ('project_title', models.CharField(max_length=50)),
                ('p_start_date', models.DateField()),
                ('p_end_date', models.DateField()),
                ('p_desc', models.TextField()),
                ('degree', models.CharField(max_length=50)),
                ('s_degree', models.CharField(blank=True, max_length=50, null=True)),
                ('school', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=50)),
                ('year_of_passing', models.IntegerField()),
                ('skill_name', models.TextField()),
            ],
        ),
    ]
