# Generated by Django 4.0 on 2024-04-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_resume_end_date_alter_resume_p_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='year_of_passing',
            field=models.IntegerField(null=True),
        ),
    ]
