# Generated by Django 4.0 on 2024-04-08 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_resume_address_alter_resume_company_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.resume')),
            ],
        ),
    ]
