# Generated by Django 4.0 on 2024-04-10 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_sendemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendemail',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.resume'),
        ),
    ]
