# Generated by Django 4.0 on 2024-04-10 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_sendemail_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendemail',
            name='message',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='sendemail',
            name='subject',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
